#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : duperemove
Version  : 0.11.1
Release  : 4
URL      : https://github.com/markfasheh/duperemove/archive/v0.11.1.tar.gz
Source0  : https://github.com/markfasheh/duperemove/archive/v0.11.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: duperemove-bin = %{version}-%{release}
Requires: duperemove-license = %{version}-%{release}
Requires: duperemove-man = %{version}-%{release}
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : sqlite-autoconf-dev

%description
# Duperemove
Duperemove is a simple tool for finding duplicated extents and
submitting them for deduplication. When given a list of files it will
hash their contents on a block by block basis and compare those hashes
to each other, finding and categorizing extents that match each
other. When given the -d option, duperemove will submit those
extents for deduplication using the Linux kernel extent-same ioctl.

%package bin
Summary: bin components for the duperemove package.
Group: Binaries
Requires: duperemove-license = %{version}-%{release}
Requires: duperemove-man = %{version}-%{release}

%description bin
bin components for the duperemove package.


%package license
Summary: license components for the duperemove package.
Group: Default

%description license
license components for the duperemove package.


%package man
Summary: man components for the duperemove package.
Group: Default

%description man
man components for the duperemove package.


%prep
%setup -q -n duperemove-0.11.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547100649
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1547100649
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/duperemove
cp LICENSE %{buildroot}/usr/share/package-licenses/duperemove/LICENSE
cp LICENSE.xxhash %{buildroot}/usr/share/package-licenses/duperemove/LICENSE.xxhash
%make_install PREFIX=/usr SBINDIR=/usr/bin

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/btrfs-extent-same
/usr/bin/duperemove
/usr/bin/hashstats
/usr/bin/show-shared-extents

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/duperemove/LICENSE
/usr/share/package-licenses/duperemove/LICENSE.xxhash

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/btrfs-extent-same.8
/usr/share/man/man8/duperemove.8
/usr/share/man/man8/hashstats.8
/usr/share/man/man8/show-shared-extents.8
