#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : duperemove
Version  : 0.12
Release  : 8
URL      : https://github.com/markfasheh/duperemove/archive/v0.12/duperemove-0.12.tar.gz
Source0  : https://github.com/markfasheh/duperemove/archive/v0.12/duperemove-0.12.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: duperemove-bin = %{version}-%{release}
Requires: duperemove-license = %{version}-%{release}
Requires: duperemove-man = %{version}-%{release}
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : sqlite-autoconf-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Duperemove
Duperemove is a simple tool for finding duplicated extents and
submitting them for deduplication. When given a list of files it will
hash their contents on a extent by extent basis and compare those hashes
to each other, finding and categorizing extents that match each
other. Optionally, a per-block hash can be applied for further duplication lookup.
When given the -d option, duperemove will submit those
extents for deduplication using the Linux kernel extent-same ioctl.

%package bin
Summary: bin components for the duperemove package.
Group: Binaries
Requires: duperemove-license = %{version}-%{release}

%description bin
bin components for the duperemove package.


%package license
Summary: license components for the duperemove package.
Group: Default

%description license
license components for the duperemove package.


%package man
Summary: man components for the duperemove package.
Group: Default

%description man
man components for the duperemove package.


%prep
%setup -q -n duperemove-0.12
cd %{_builddir}/duperemove-0.12
pushd ..
cp -a duperemove-0.12 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689811206
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}

pushd ../buildavx2
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1689811206
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/duperemove
cp %{_builddir}/duperemove-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/duperemove/cca1a98df1d42b70d0e705fe296bf45230196c14 || :
cp %{_builddir}/duperemove-%{version}/LICENSE.xxhash %{buildroot}/usr/share/package-licenses/duperemove/faa50d629c27ea217aba549a466c7082430e1528 || :
pushd ../buildavx2/
%make_install_v3 PREFIX=/usr SBINDIR=/usr/bin
popd
%make_install PREFIX=/usr SBINDIR=/usr/bin
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/btrfs-extent-same
/V3/usr/bin/duperemove
/V3/usr/bin/hashstats
/V3/usr/bin/show-shared-extents
/usr/bin/btrfs-extent-same
/usr/bin/duperemove
/usr/bin/hashstats
/usr/bin/show-shared-extents

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/duperemove/cca1a98df1d42b70d0e705fe296bf45230196c14
/usr/share/package-licenses/duperemove/faa50d629c27ea217aba549a466c7082430e1528

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/btrfs-extent-same.8
/usr/share/man/man8/duperemove.8
/usr/share/man/man8/hashstats.8
/usr/share/man/man8/show-shared-extents.8
